### PR TITLE
Delete an incorrect blender logo link

### PR DESCRIPTION
**Pull request by dzikoysk**

### CODE REVIEW

**Comment by Dancovich** [comment]
The official logo changed locations, the new location is: https://download.blender.org/institute/logos/blenderlogocolor.png

Could you please include the correct link in your pull request?

**Comment by dzikoysk** [comment]
I've seen that, but this logo is really huge:

Preview

Are you sure?

**Comment by Dancovich** [comment]
Humm, I see that now. In that case I'll take a look if there's a smaller official icon I can use. I'm trying to follow Blender rules on using the official icon.

Thanks for reporting, I didn't see the old icon wasn't up anymore.

**Comment by dzikoysk** [comment]
With `http://download.blender.org/institute/logos/blenderlogo.png`:

obraz

Now it is unevenly :(

**Comment by RUSshy** [comment]
is logo really needed for readme ?

**Pull request closed without merging**
